services:
  upserv:
    build: .
    ports:
      - "${PORT}:8080"
    environment:
      - UPLOAD_PATH=${UPLOAD_PATH}
      - BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME}
      - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}
    volumes:
      - ${HOST_UPLOAD_PATH}:${UPLOAD_PATH}
    restart: always
    container_name: ${UPNAME}
